# Python Programming Basic Assignment

## Programming Assignment 8 Solutions

1.Write a Python Program to Add Two Matrices?

In [2]:
import numpy as np

def matrices_input(no_of_matrices, rows, columns):
    
    try:
    
        dict_of_matrices = {}

        for num in range(0, no_of_matrices): 

            user_input = input(f"Enter the elements you want in matrix {num+1} separated by space: ")
            user_list = user_input.split()

            elements_list = list(map(int,user_list))

            dict_of_matrices[f"matrix_{num+1}"] = np.array(elements_list).reshape(rows,columns)

        return dict_of_matrices
    
    except Exception as e:
        print("1. Error occurred : " + str(e))


def add_matrices(input_dict, rows, columns):
    
    try: 
        
        sum_of_matrices = np.zeros((rows, columns))
        
        for values in input_dict.values():
            sum_of_matrices = np.add(sum_of_matrices, values)

        return sum_of_matrices
    
    except Exception as e:
        print("2. Error occurred : " + str(e))
        
try: 
    
    no_of_matrices = int(input("Enter the number of matrices you want to enter: "))
    rows = int(input("Enter the number of rows you want in matrices : "))
    columns = int(input("Enter the number of columns you want in matrices : "))

    input_dict = matrices_input(no_of_matrices, rows, columns)
    result = add_matrices(input_dict, rows, columns)

    print(f"\nThe matrices given by user are : \n{input_dict.items()}\n")


except Exception as e:
    print("3. Error occurred : " + str(e))
    
else:
    print(f"The sum of the matrices is given as : \n{result}")



Enter the number of matrices you want to enter: 2
Enter the number of rows you want in matrices : 2
Enter the number of columns you want in matrices : 2
Enter the elements you want in matrix 1 separated by space: 1 2 3 4
Enter the elements you want in matrix 2 separated by space: 1 2 3 4

The matrices given by user are : 
dict_items([('matrix_1', array([[1, 2],
       [3, 4]])), ('matrix_2', array([[1, 2],
       [3, 4]]))])

The sum of the matrices is given as : 
[[2. 4.]
 [6. 8.]]


2.Write a Python Program to Multiply Two Matrices?

In [3]:
import numpy as np

def matrices_input():
    
    try:
    
        dict_of_matrices = {}

        for num in range(0,2): 
            
            rows = int(input(f"Enter the number of rows you want in matrix {num+1} : "))
            columns = int(input(f"Enter the number of columns you want in matrix {num+1} : "))

            user_input = input(f"Enter the elements you want in matrix {num+1} separated by space: ")
            user_list = user_input.split()

            elements_list = list(map(int,user_list))

            dict_of_matrices[f"matrix_{num+1}"] = np.array(elements_list).reshape(rows,columns)

        return dict_of_matrices
    
    except Exception as e:
        print("1. Error occurred : " + str(e))


def multiply_matrices(input_dict):
    
    try: 
        
        matrix_1 = input_dict.get("matrix_1")
        matrix_2 = input_dict.get("matrix_2")
        
        multiply_of_matrices = np.matmul(matrix_1, matrix_2)
        
        return multiply_of_matrices
    
    except Exception as e:
        print("2. Error occurred : " + str(e))
        
try: 
    
    print("Enter any two matrices for multiplication !!")

    input_dict = matrices_input()
    result = multiply_matrices(input_dict)

    print(f"\nThe matrices given by user are : \n{input_dict.items()}\n")


except Exception as e:
    print("3. Error occurred : " + str(e))
    
else:
    print(f"The multiplication of the matrices is given as : \n{result}")



Enter any two matrices for multiplication !!
Enter the number of rows you want in matrix 1 : 2
Enter the number of columns you want in matrix 1 : 4
Enter the elements you want in matrix 1 separated by space: 1 2 3 4 5 6 7 8
Enter the number of rows you want in matrix 2 : 4
Enter the number of columns you want in matrix 2 : 3
Enter the elements you want in matrix 2 separated by space: 1 2 3 4 5 6 7 8 9 10 11 12

The matrices given by user are : 
dict_items([('matrix_1', array([[1, 2, 3, 4],
       [5, 6, 7, 8]])), ('matrix_2', array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]]))])

The multiplication of the matrices is given as : 
[[ 70  80  90]
 [158 184 210]]


3.Write a Python Program to Transpose a Matrix?

In [9]:
import numpy as np

def matrices_input():
    
    try:

        rows = int(input(f"Enter the number of rows you want in matrix : "))
        columns = int(input(f"Enter the number of columns you want in matrix : "))

        user_input = input(f"Enter the elements you want in matrix separated by space: ")
        user_list = user_input.split()

        elements_list = list(map(int,user_list))

        matrix = np.array(elements_list).reshape(rows,columns)

        return matrix
    
    except Exception as e:
        print("1. Error occurred : " + str(e))
        
try:
    
    input_matrix = matrices_input()
    transposed_matrix = np.transpose(input_matrix)
    
    
except Exception as e:
    print("2. Error occurred : " + str(e))
    
else:
    print(f"The input matrix given by user is : \n {input_matrix}\n")
    print(f"The transposed matrix given by user is : \n {transposed_matrix}\n")
    

Enter the number of rows you want in matrix : 3
Enter the number of columns you want in matrix : 3
Enter the elements you want in matrix separated by space: 1 2 3 4 5 6 7 8 9
The input matrix given by user is : 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

The transposed matrix given by user is : 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]



4.Write a Python Program to Sort Words in Alphabetic Order?

In [20]:
def sorting (user_input):
    
    try:
        
        user_list = user_input.split()

        user_list_copy = user_list.copy()

        user_list_copy.sort()
        
        return user_list_copy
    
    except Exception as e:
        print(f"1. Error occurred: " + str(e))
        
try:
    user_input = input(f"Enter any sentence and press enter:  ")
    
except Exception as e:
    print(f"2. Error occurred: " + str(e))
    
else:
    print(f"The sorted words in alphabetic order are: {sorting(user_input)}")

Enter any sentence and press enter:  My name is Dhruv Gautam
The sorted words in alphabetic order are: ['Dhruv', 'Gautam', 'My', 'is', 'name']


5.Write a Python Program to Remove Punctuation From a String?

In [24]:

punctuation = '''''!()-[]{};:'"\,<>./?@#$%^&*_~'''  

def remove_punc(string):
    
    try:
    
        no_punc_string = " " 

        for char in string:  
            if char not in punctuation:
                no_punc_string = no_punc_string + char

        return no_punc_string
    
    except Exception as e:
        print("1. Error occurred: " + str(e))

try:
    user_input = input("Enter a string: ")
    
    print(f"The string given by user is: \n{user_input}\n")
    
    result = remove_punc(user_input)
    
except Exception as e:
    print("2. Error occurred: " + str(e))
    
else:
    print(f"The string after removing punctuation is given as: \n{result}\n")

Enter a string: my!@#$ name #$%#@ is ....... dhruv
The string given by user is: 
my!@#$ name #$%#@ is ....... dhruv

The string after removing punctuation is given as: 
 my name  is  dhruv

